//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




// Should have a userID and perhaps a list of notes with a note Table in DB so the user could make multiple notes for and event 
// but this is just for demo

namespace v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
      
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Category { get; set; }
        public string Note { get; set; }
    }
}
